######################## default configuration ####################
baseURL = "https://blog.robotmk.org"
title = "Robotmk | Blog"
theme = "logbook"
# post pagination
paginate = "5"
# post excerpt
summaryLength = "50"
# google analytics
# googleAnalytics = "" # Ex: UA-123-45
# disqus short name
# disqusShortname = "themefisher-template" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]

[markup]
[markup.goldmark.renderer]
unsafe= true

[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]

[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"


######################### site variables ##############################
# customize your color and font from here.
[params.variables]
color_primary = "#00D391"
body_color = "#fff"
text_color = "#696c6d"
text_color_dark = "#1c1d1f"
text_color_light = "#888c8e"
border_color = "#ddd"
black = "#000"
white = "#fff"
light = "#f0f0f0"

# font variables
# base font size for full website, 
font_size = "16px" # default is 16px

# Font Scale Sizes
# "minorSecond": 1.067,
# "majorSecond": 1.125,
# "minorThird": 1.2,
# "majorThird": 1.25,
# "perfectFourth": 1.333,
# "augmentedFourth": 1.414,
# "perfectFifth": 1.5,
# "goldenRatio": 1.618
font_scale = "1.2" # default is "minorThird": 1.2

# go to https://fonts.google.com/ to find the font you want to use. select your font and copy only the bold part from the URL. and paste it here.

# example: "Open Sans:wght@400;500;600"
font_primary = "Open Sans:wght@400"
font_primary_type = "sans-serif" # [serif/sans-serif]
font_secondary = "Montserrat:wght@400"
font_secondary_type = "sans-serif" # [serif/sans-serif]
icon_font = "Font Awesome 5 Free"

