################################### English language #####################################
[en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# footer content
footer_content = "Robot Framework test integration for E2E monitoring in Checkmk."
# copyright
copyright = "© 2021 [ELABIT GmbH](https://www.elabit.de/)"

################################### German language #####################################
[de]
languageName = "German"
languageCode = "de-DE"
contentDir = "content/german"
weight = 2
home = "Home"
# footer content
footer_content = "Robot Framework test integration for E2E monitoring in Checkmk."
# copyright
copyright = "© 2021 [ELABIT GmbH](https://www.elabit.de/)"