############### German navigation ################

[[main]]
weight = 1
name = "blog"
url = "/"

[[main]]
name = "Über Robotmk"
url = "https://www.robotmk.org"
weight = 2

[[main]]
name = "Professional Support"
url = "https://www.robotmk.org/pages/professionalsupport"
weight = 3


# footer menu  --------------------------------------------------------
[[footer]]
name = "Über Robotmk"
url = "https://www.robotmk.org"
weight = 1

[[footer]]
name = "Professional Support"
url = "https://www.robotmk.org/pages/professionalsupport"
weight = 2

[[footer]]
name = "Datenschutzerklärung"
url = "privacy-policy"
weight = 3

[[footer]]
name = "Impressum"
url = "imprint"
weight = 4